# Model Architecture Configuration

# 3D U-Net Configuration
unet3d:
  in_channels: 1
  out_channels: 1
  base_channels: 64
  channel_mults: [1, 2, 4, 8]
  num_res_blocks: 2
  time_emb_dim: 256
  dropout: 0.1
  attention_resolutions: [2, 4]

# Diffusion Model Configuration
diffusion:
  timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  beta_schedule: "linear"  # Options: linear, quadratic, cosine

# Model Variants
variants:
  lightweight:
    base_channels: 32
    channel_mults: [1, 2, 4]
    num_res_blocks: 1
  
  standard:
    base_channels: 64
    channel_mults: [1, 2, 4, 8]
    num_res_blocks: 2
  
  large:
    base_channels: 96
    channel_mults: [1, 2, 4, 8]
    num_res_blocks: 3
