# Training Configuration for Medical Image Enhancement

# Data configuration
data:
  train_dir: "data/processed/train"
  val_dir: "data/processed/val"
  train_list: null  # Optional: path to JSON with file list
  val_list: null
  patch_size: [64, 64, 64]  # 3D patch size for training

# Model configuration
model:
  in_channels: 1
  out_channels: 1
  base_channels: 64
  channel_mults: [1, 2, 4, 8]  # Channel multipliers for each level
  num_res_blocks: 2  # Number of residual blocks per level
  time_emb_dim: 256
  dropout: 0.1
  attention_resolutions: [2, 4]  # Levels to apply attention

# Diffusion configuration
diffusion:
  timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  beta_schedule: "linear"  # Options: linear, quadratic, cosine

# Training configuration
training:
  epochs: 100
  batch_size: 4
  learning_rate: 0.0001
  min_lr: 0.000001
  weight_decay: 0.01
  grad_clip: 1.0
  num_workers: 4
  
  # Checkpointing
  output_dir: "models/pretrained"
  save_interval: 10  # Save checkpoint every N epochs
  sample_interval: 5  # Generate sample every N epochs
  resume_from: null  # Path to checkpoint to resume from
  
  # Optimization
  warmup_epochs: 5
  use_amp: true  # Automatic Mixed Precision
